### ISSUE TITLE
Unable to enable add-on via script

### ISSUE THREAD

**Issue by joezhou099** [EPhysLab-UVigo/VisualSPHysics#13]
Hi, i used bpy.ops.preferences.addon_install() to install visualsphysics.zip and enable('VisualSPHysics'). However, when i check('VisualSPHysics'), the status is still false and no error reported in the panel. I have compiled it on my centos 7.6.1810 aarch64, and it was successful. May i know the reason,pls?

**Comment by Rodland** [comment]
Which Blender version are you using? Have you tried launching Blender from a terminal and checking if some error information is shown in the terminal when you try to install the addon?

**Comment by joezhou099** [comment]
2.82a
Because i installed blender in my server without GUI, i can only check it with the script. Tricky thing is that check('VisualSPHyiscs') gives false status without any warning or error, i am sure that the blender read Visualsphysics.py, because when i modified the code of visualsphysics.py, it gave errors.

**Comment by Rodland** [comment]
After addon_install() are the addon files effectively placed under `~/.config/blender/2.82/scripts/addons`? If so, could it be a problem with the shared libraries? You can make a:

`ldd ~/.config/blender/2.82/scripts/addons/diffuseparticles.so`
`ldd ~/.config/blender/2.82/scripts/addons/vtkimporter.so` 

in order to check if there's some missing dependency.

**Comment by joezhou099** [comment]
Yes, Because i run blender from a public shared folder, the installation path is /path/to/public_shared_folder_blender/2.8/script/addon instead of local folder(.config). It works on x86, but does not work on aarch64.

Also, there is no dependency issue related to shared libraries.

**Comment by joezhou099** [comment]
I used Python -m pdb c.py where c.py only contains the function of enabe and check('VisualSPHysics'), and found out that addon_utils.py exited at 371 row, which means that it did not enter the following register modules steps. Could you have a look at this, pls? Cheers

**Comment by joezhou099** [comment]
As far as i see, blender 2.8× removed the function bpy.utils.register_modules(), which is in Visualsphysics.py, so i guess this may cause the issue

**Comment by Rodland** [comment]
The bpy.utils.register_modules() function is no longer used. Are you using an old version of the code?

**Comment by joezhou099** [comment]
Ohh, yes, thank you very much), Silly mistake, blind me😂
