### ISSUE TITLE
Unable to install VisualSPhysics in latest version of blender

### ISSUE THREAD

**Issue by robeche** [EPhysLab-UVigo/VisualSPHysics#6]
I get the following error when i try to enable the plugin in blender...

![imagen](https://user-images.githubusercontent.com/45792405/64866589-04e4dc00-d63c-11e9-95f1-e85ae093feda.png)

**Comment by robeche** [comment]
ok, i retried using blender 2.79 and it works... i guess there is some update needed for blender 2.8

**Comment by luoleibuku** [comment]
![Snipaste_2019-09-20_14-41-25](https://user-images.githubusercontent.com/31950124/65305044-c196ea00-dbb4-11e9-81d8-05d22570df66.jpg)
2.79 still cannot work well
![Snipaste_2019-09-20_14-41-25](https://user-images.githubusercontent.com/31950124/65305095-e12e1280-dbb4-11e9-9fe8-c1b269e3a4fb.jpg)

**Comment by Rodland** [comment]
Hi! I've uploaded a new release ([v1.1](https://github.com/EPhysLab-UVigo/VisualSPHysics/releases/tag/v1.1)) that supports Blender 2.80.

**Comment by joezhou099** [comment]
Dear Developer,
I used (gcc-4.8.5, VTK of Paraview-4.4.0, cmake 2.8.12.2) to compile the code successfully. But when i add it on blender 2.80, it gives me an error "diffuseparticles.so: undefined symbol: _ZN17vtkPolyDataReader3NewEv". What am i supposed to do? Much appreciated!

**Comment by Rodland** [comment]
It looks like there's some missing vtk shared library. You can make:

`ldd /path/to/diffuseparticles.so`

To identify the missing library. If the library is actually in your system but VisualSPHysics cannot find it, you should add its location to the library search path:

`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/the/missing/library`

**Comment by cindylly** [comment]
I get the following error when I try to add-on the plugin in blender 2.82
![0504212352](https://user-images.githubusercontent.com/64787539/80970451-c364a380-8e4d-11ea-9bd1-8ea0bee2de36.jpg)
...
![0504212352](https://user-images.githubusercontent.com/64787539/80970451-c364a380-8e4d-11ea-9bd1-8ea0bee2de36.jpg)
