### ISSUE TITLE
Blender 2.8 - Python 3.7

### ISSUE THREAD

**Issue by jb4earth** [EPhysLab-UVigo/VisualSPHysics#7]
There is no VTK module for Python 3.7 (yet) and downgrading Blender seems a non-ideal solution.  Any better ideas?

**Comment by jb4earth** [comment]
Following up, it seems like this was an admin or procedure issue.   Solution is now posted at https://blender.stackexchange.com/questions/157302/blender-2-8-windows-10-python-import-module-fails-pip-install-module-fail

**Comment by joezhou099** [comment]
I used the VTK module from paraview, and the code can be compiled successfully

**Comment by Rodland** [comment]
VisualSPHysics does not use the VTK Python module but the VTK C++ library instead.
