### ISSUE TITLE
import error: undefined symbol: _ZN17vtkPolyDataReader3NewEv

### ISSUE THREAD

**Issue by joezhou099** [EPhysLab-UVigo/VisualSPHysics#8]
Dear Developer,
I used (gcc-4.8.5, VTK of Paraview-4.4.0, cmake 2.8.12.2) to compile the code successfully. But when i add it on blender 2.80, it gives me an error "diffuseparticles.so: undefined symbol: _ZN17vtkPolyDataReader3NewEv". What am i supposed to do? Much appreciated!

**Comment by joezhou099** [comment]
May i know your gcc cmake version pls?thx

**Comment by Rodland** [comment]
I haven't tested the current code with GCC versions prior to v6 neither CMake <v3.

**Comment by joezhou099** [comment]
Is there an requirement for glibc version? My glibc version is 2.17 and i used gcc-6.4.0 to compile. ldd /path/to/diffuseparticles.so, it showed 'GLIBCXX 3.4.20' 'GLIBCXX 3.4.21' 'CXX 1.3.9' not found. 

BTW when i tested one cpp file (e.g. FluidData.cpp) it gave me many undefined reference such as 'undefined reference to 'vtkPolyDataReader::New()'' but i certainly use -I to link the VTK_INCLUDE_DIR that contains the header file. not sure whether this was caused by GLIBC or not.

Could you help me with this pls? thank you very much!
